youtube/project/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('youtube.urls')),  # root/index is redirected to youtube.urls
    path('youtube-admin/', admin.site.urls),
    path(r'accounts/', include('django_registration.backends.activation.urls')),
    path(r'accounts/', include('django.contrib.auth.urls')),
]

youtube/youtube/urls.py
from django.urls import path

from . import views

app_name = 'youtube'
urlpatterns = [
    path('', views.index, name='index'),
    path('results', views.search_results, name='search_results'),
    path('video/view/<int:pk>', views.video_view, name='video_view'),
    path('video/view/like/<int:pk>', views.video_like, name='video_like'),
    path('video/myvideos', views.video_myvideos, name='video_myvideos'),
    path('video/new', views.video_new, name='video_new'),
    path('video/view/addtoplaylist/<int:pk>', views.video_addtoplaylist, name='video_addtoplaylist'),
    path('addtoplaylist/<int:pk>', views.video_addtoplaylist_fromindex, name='video_addtoplaylist_fromindex'),
    path('video/myplaylist', views.video_myplaylist, name='video_myplaylist'),
    path('video/deletefromplaylist/<int:pk>', views.video_deletefromplaylist, name='video_deletefromplaylist'),
    path('video/edit/<int:pk>', views.video_edit, name='video_edit'),
    path('video/delete/<int:pk>', views.video_delete, name='video_delete'),
]

youtube/youtube/models.py
from django.db import models
from django.contrib.auth.models import User


class Video(models.Model):
    title = models.TextField()
    description = models.CharField(max_length=256)
    source = models.URLField(blank=True, null=False)
    likes = models.BigIntegerField(blank=True, null=True)
    views = models.BigIntegerField(blank=True, null=True)
    added = models.DateTimeField(auto_now_add=True, null=True)
    edited = models.DateTimeField(auto_now=True, null=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE,
                             blank=True, null=True)

    def __str__(self):
        return f'{self.title} - submitted by {self.user}'

    class Meta:
        ordering = ['-added']


class Playlist(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE,
                             blank=True, null=True)
    video = models.ForeignKey(Video, on_delete=models.CASCADE,
                              blank=True, null=True)

    def __str__(self):
        return f'{self.user} - {self.video}'

youtube/youtube/forms.py
from django.forms import ModelForm

from .models import Video


class VideoForm(ModelForm):
    class Meta:
        model = Video
        fields = ['title', 'description', 'source', 'likes', 'views']
        # fields = ['title', 'description', 'source']

youtube/youtube/views.py
import json
from random import random

from django.contrib import messages
from django.contrib.auth.models import AnonymousUser
from django.forms import model_to_dict
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, render, redirect
from django.contrib.auth.decorators import login_required

from youtube.forms import VideoForm
from youtube.models import Video, Playlist


def index(request):
    # if request.method == 'GET' and 'key' in request.GET:
    #     key = request.GET['key']
    #     if key is not None and key != '':
    #         videos = Video.objects.filter(title__icontains=key)
    #         print(videos)
    #     else:
    #         videos = Video.objects.all()
    # else:
    videos = Video.objects.all()

    all_videos = []
    row_video = {'col1': None, 'col2': None, 'col3': None}

    for video in videos:

        html_video = {}
        html_video['id'] = video.id
        html_video['title'] = video.title
        html_video['description'] = video.description
        html_video['views'] = video.views
        # html_video['user'] = model_to_dict(video.user)
        html_video['user'] = video.user
        html_video['added'] = video.added
        html_video['source'] = "http://img.youtube.com/vi/" + video.source.split('?')[0].split('/')[-1] + "/hqdefault.jpg"
        # "http://img.youtube.com/vi/K5PXiNpvfX0/hqdefault.jpg" https://www.youtube.com/embed/K5PXiNpvfX0?si=qZL7BfYLtuXQ_4p1
        video = html_video

        if not row_video['col1']:
            row_video['col1'] = video
        elif not row_video['col2']:
            row_video['col2'] = video
        else:
            row_video['col3'] = video
            all_videos.append(row_video)
            row_video = {'col1': None, 'col2': None, 'col3': None}

    if row_video['col1']:  # for last incomplete row
        all_videos.append(row_video)

    return render(request, 'youtube/index.html', {'videos': all_videos})


def search_results(request):
    if request.method == 'GET' and 'key' in request.GET:
        key = request.GET['key']
        if key is not None and key != '':
            videos = Video.objects.filter(title__icontains=key)
            # print(videos)
        else:
            videos = Video.objects.all()
    else:
        videos = Video.objects.all()

    all_videos = []
    row_video = {'col1': None, 'col2': None, 'col3': None}

    for video in videos:

        html_video = {}
        html_video['id'] = video.id
        html_video['title'] = video.title
        html_video['description'] = video.description
        html_video['views'] = video.views
        # html_video['user'] = model_to_dict(video.user)
        html_video['user'] = video.user
        html_video['added'] = video.added
        html_video['source'] = "http://img.youtube.com/vi/" + video.source.split('?')[0].split('/')[-1] + "/hqdefault.jpg"
        # "http://img.youtube.com/vi/K5PXiNpvfX0/hqdefault.jpg" https://www.youtube.com/embed/K5PXiNpvfX0?si=qZL7BfYLtuXQ_4p1
        video = html_video

        if not row_video['col1']:
            row_video['col1'] = video
        elif not row_video['col2']:
            row_video['col2'] = video
        else:
            row_video['col3'] = video
            all_videos.append(row_video)
            row_video = {'col1': None, 'col2': None, 'col3': None}

    if row_video['col1']:  # for last incomplete row
        all_videos.append(row_video)

    if request.method == 'GET' and 'key' in request.GET:
        # videos = {}
        # html = ''
        # #################################################################################
        # # create the new html text here that will replace <div id="videos"> contents
        # html = html + """<h1 class ="fw-normal text-center">Welcome</h1>"""
        # #################################################################################
        # videos['html'] = html
        # return HttpResponse(
        #     json.dumps(videos, default=str),
        #     content_type="application/json"
        # )
        return render(request, 'youtube/index_results.html', {'videos': all_videos})
    else:
        return render(request, 'youtube/index_results.html', {'videos': all_videos})


def video_view(request, pk):
    video = get_object_or_404(Video, pk=pk)
    video.views = video.views + 1
    video.save()
    video_viewed = get_object_or_404(Video, pk=pk)
    video_viewed.source = video_viewed.source + "&autoplay=1"

    videos = Video.objects.all()

    all_videos = []
    row_video = {'col1': None, 'col2': None, 'col3': None}

    for video in videos:
        if video.id == pk:
            continue

        html_video = {}
        html_video['id'] = video.id
        html_video['title'] = video.title
        html_video['description'] = video.description
        html_video['views'] = video.views
        html_video['user'] = video.user
        html_video['added'] = video.added
        html_video['source'] = "http://img.youtube.com/vi/" + video.source.split('?')[0].split('/')[
            -1] + "/hqdefault.jpg"
        # "http://img.youtube.com/vi/K5PXiNpvfX0/hqdefault.jpg" https://www.youtube.com/embed/K5PXiNpvfX0?si=qZL7BfYLtuXQ_4p1
        video = html_video

        if not row_video['col1']:
            row_video['col1'] = video
        elif not row_video['col2']:
            row_video['col2'] = video
        else:
            row_video['col3'] = video
            all_videos.append(row_video)
            row_video = {'col1': None, 'col2': None, 'col3': None}

    if row_video['col1']:  # for last incomplete row
        all_videos.append(row_video)

    return render(request, 'youtube/video_view.html', {'video': video_viewed, 'videos': all_videos})


# @login_required
def video_like(request, pk):
    if isinstance(request.user, AnonymousUser):
        video_viewed_json = {}
        video_viewed_json['status'] = 0
        # video_viewed_json['likes'] = video_viewed.likes
        return HttpResponse(
            json.dumps(video_viewed_json),
            content_type="application/json"
        )

    video = get_object_or_404(Video, pk=pk)
    video.likes = video.likes + 1
    video.save()
    video_viewed = get_object_or_404(Video, pk=pk)

    video_viewed_json = {}
    video_viewed_json['status'] = 1
    video_viewed_json['likes'] = video_viewed.likes
    return HttpResponse(
        json.dumps(video_viewed_json),
        content_type="application/json"
    )


@login_required
def video_myvideos(request):
    videos = Video.objects.filter(user=request.user)

    my_videos = []
    row_video = {'col1': None, 'col2': None, 'col3': None}

    for video in videos:

        html_video = {}
        html_video['id'] = video.id
        html_video['title'] = video.title
        html_video['description'] = video.description
        html_video['views'] = video.views
        html_video['user'] = video.user
        html_video['added'] = video.added
        html_video['source'] = "http://img.youtube.com/vi/" + video.source.split('?')[0].split('/')[
            -1] + "/hqdefault.jpg"
        # "http://img.youtube.com/vi/K5PXiNpvfX0/hqdefault.jpg" https://www.youtube.com/embed/K5PXiNpvfX0?si=qZL7BfYLtuXQ_4p1
        video = html_video

        if not row_video['col1']:
            row_video['col1'] = video
        elif not row_video['col2']:
            row_video['col2'] = video
        else:
            row_video['col3'] = video
            my_videos.append(row_video)
            row_video = {'col1': None, 'col2': None, 'col3': None}

    if row_video['col1']:  # for last incomplete row
        my_videos.append(row_video)

    return render(request, 'youtube/video_myvideos.html', {'videos': my_videos})


@login_required
def video_new(request):
    form = VideoForm(request.POST or None)

    if form.is_valid():
        form = form.save(commit=False)
        form.user = request.user
        form.save()
        # messages.success(request, 'Added new video')
        return redirect('youtube:video_myvideos')

    return render(request, 'youtube/video_form.html', {'form': form})


@login_required
def video_edit(request, pk):
    video = get_object_or_404(Video, pk=pk, user=request.user)
    form = VideoForm(request.POST or None, instance=video)

    if form.is_valid():
        form = form.save(commit=False)
        form.user = request.user
        form.save()
        # messages.success(request, 'Updated video')
        return redirect('youtube:video_myvideos')

    return render(request, 'youtube/video_form.html', {'video': video, 'form': form})


@login_required
def video_delete(request, pk):
    video = get_object_or_404(Video, pk=pk, user=request.user)
    video.source = video.source + "&autoplay=1"

    if request.method == 'POST':
        video.delete()
        # messages.success(request, 'Deleted video')
        return redirect('youtube:video_myvideos')

    return render(request, 'youtube/video_confirm_delete.html', {'video': video})


def video_addtoplaylist(request, pk):
    if isinstance(request.user, AnonymousUser):
        video_viewed_json = {}
        video_viewed_json['status'] = 0
        return HttpResponse(
            json.dumps(video_viewed_json),
            content_type="application/json"
        )

    video = get_object_or_404(Video, pk=pk)
    video_addedtoplaylist = Playlist.objects.filter(user=request.user, video=video)
    video_viewed_json = {}
    video_viewed_json['message'] = "Video is already in playlist."
    if not video_addedtoplaylist:
        video_addedtoplaylist = Playlist()
        video = get_object_or_404(Video, pk=pk)
        video_addedtoplaylist.user = request.user
        video_addedtoplaylist.video = video

youtube/youtube/templates/youtube/video_confirm_delete.html
{% extends 'base.html' %}
{% load humanize %}

{% block content %}
    <div>
        <div id="video">
            <div>
<!--            <h1 class="fw-bold">YouTube Demo Application</h1>-->
<!--            <h5 class="fw-light">Watch, like and upload your own videos!</h5>-->
                <iframe width="780" height="470" src={{ video.source }} title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
                <div class="video_details">
                    <p class="fw-normal text-light" style="font-size: 20px; padding: 0px; margin: 0px;">{{ video.title }}</p>
                    <p class="fw-normal text-light" style="font-size: 12px; padding: 0px; margin: 0px;">Posted by {{ video.user }} {{ video.added|timesince }} ago</p>
                    <p class="fw-light text-light" style="font-size: 14px; padding: 0px; margin-top: 10px;">{{ video.description }}</p>
                    <div class="container">
                        <input type="hidden" name="pk" value={{video.id}} id='pk'>
                        <div class="row">
                            <div class="col-lg-4">
                                <p class="fw-normal text-light text-center" style="font-size: 15px;"><span class="bi bi-hand-thumbs-up" style="font-size: 18px;"></span><span>&nbsp;&#8226;&nbsp;{{ video.likes }} likes</span></p>
                            </div>
                            <div class="col-lg-4">
                                <p class="fw-normal text-light text-center" style="font-size: 15px;"><span class="bi bi-person-video2" style="font-size: 18px;"></span>&nbsp;{{ video.views }} views&nbsp;</p>
                            </div>
                            <div class="col-lg-4" style="padding: 0px; margin: 0px;">
                                <form method="post">
                                    {% csrf_token %}
                                    <div class="d-flex justify-content-end">
                                        <button type="submit" class="btn btn-danger text-center" style="font-size: 18px; margin-bottom: 16px;">&nbsp;Continue to delete&nbsp;</button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <br>
        <br>
    </div>

{% endblock %}

youtube/youtube/templates/youtube/video_myplaylist.html
{% extends 'base.html' %}
{% load humanize %}

{% block content %}
    <div>
        <div id="hero">
            <div>
            <h1 class="fw-bold">YouTube Demo Application</h1>
            <h5 class="fw-light">Watch, like and upload your own videos!</h5>
            </div>
        </div>
        <br>
        <br>
    </div>

    {% if request.user.is_authenticated %}
        <br>
        <div>
            <h1 class="fw-normal text-center">Welcome {{ request.user.username }}!</h1>
            <h5 class="fw-light text-center">Your playlist.</h5>
        </div>
        <br>
        <br>
    {% endif %}

<!--    <div class="container" style="margin-top: 0px; margin-bottom: 30px;">-->
<!--        <div class="row">-->
<!--            <div class="col-lg-4">-->
<!--            </div>-->
<!--            <div class="col-lg-4">-->
<!--                <div class="d-flex justify-content-center">-->
<!--                    <a href="{% url 'youtube:video_new' %}" class="btn btn-success text-center" style="font-size: 22px;">&nbsp;<i class="bi bi-plus-lg" style="font-size: 20px;"></i></span>&nbsp;Add a new video&nbsp;</a>-->
<!--                </div>-->
<!--            </div>-->
<!--            <div class="col-lg-4">-->
<!--            </div>-->
<!--        </div>-->
<!--    </div>-->

    {% if videos %}
    <div class="container">
        {% for video in videos %}
        <div class="row">
            <div class="col-lg-4">
                {% if video.col1 %}
                    <div class="card video-content">
                        <a href="{% url 'youtube:video_view' video.col1.id %}">
                            <div class="d-flex justify-content-center" style="">
<!--                                <iframe width="560" height="280" src={{ video.col1.source }} title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>-->
                                <img class="card-img-top" src={{ video.col1.source }} title="YouTube Video" alt="YouTube Video" width="560" height="280"/>
                            </div>
                        </a>
                        <div class="card-body">
                            {% if video.col1.title|length <= 40 %}
                                <h4 class="card-title" style="font-size: 20px; padding: 0px; margin: 0px;">{{ video.col1.title }}, You Must Watch This</h4>
                            {% else %}
                                <h4 class="card-title" style="font-size: 20px; padding: 0px; margin: 0px;">{{ video.col1.title }}</h4>
                            {% endif %}
                            <p class="text-muted" style="font-size: 14px; padding: 0px; margin-top: 10px;">Posted by {{ video.col1.user }} {{ video.col1.added|timesince }} ago</p>
                            <small class="card-text">{{ video.col1.description }}</small>
                        </div>
                        <div class="card-footer d-flex justify-content-center">
                            <div class="container" style="padding: 0px; margin: 0px;">
                                <div class="row">
                                    <div class="col-lg-4" >
                                        <p class="fw-normal text-body text-start" style="font-size: 15px; padding: 0px; margin: 0px;"><span class="bi bi-person-video2" style="font-size: 18px;"></span>{{ video.col1.views }} views</p>
                                    </div>
                                    <div class="col-lg-4" >
<!--                                        <p class="fw-normal text-body text-center" style="font-size: 15px; padding: 0px; margin: 0px;"><a href="{% url 'youtube:video_edit' video.col1.id %}" class="bi bi-pen text-dark" style="font-size: 18px;"></a>&nbsp;&#8226;&nbsp;Edit</p>-->
                                    </div>
                                    <div class="col-lg-4">
                                        <p class="fw-normal text-body text-end" style="font-size: 15px; padding: 0px; margin: 0px;"><a href="{% url 'youtube:video_deletefromplaylist' video.col1.id %}" class="bi bi-trash text-dark" style="font-size: 18px;"></a>&nbsp;&#8226;&nbsp;Delete</p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endif %}
            </div>
            <div class="col-lg-4">
                {% if video.col2 %}
                    <div class="card video-content">
                        <a href="{% url 'youtube:video_view' video.col2.id %}">
                            <div class="d-flex justify-content-center" style="">
    <!--                            <iframe width="560" height="280" src={{ video.col2.source }} title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>-->
                                <img class="card-img-top" src={{ video.col2.source }} title="YouTube Video" alt="YouTube Video" width="560" height="280"/>
                            </div>
                        </a>
                        <div class="card-body">
                            {% if video.col2.title|length <= 40 %}
                                <h4 class="card-title" style="font-size: 20px; padding: 0px; margin: 0px;">{{ video.col2.title }}, You Must Watch This</h4>
                            {% else %}
                                <h4 class="card-title" style="font-size: 20px; padding: 0px; margin: 0px;">{{ video.col2.title }}</h4>
                            {% endif %}
                            <p class="text-muted" style="font-size: 14px; padding: 0px; margin-top: 10px;">Posted by {{ video.col2.user }} {{ video.col2.added|timesince }} ago</p>
                            <small class="card-text">{{ video.col2.description }}</small>
                        </div>
                        <div class="card-footer d-flex justify-content-center">
                            <div class="container" style="padding: 0px; margin: 0px;">
                                <div class="row">
                                    <div class="col-lg-4" >
                                        <p class="fw-normal text-body text-start" style="font-size: 15px; padding: 0px; margin: 0px;"><span class="bi bi-person-video2" style="font-size: 18px;"></span>{{ video.col2.views }} views</p>
                                    </div>
                                    <div class="col-lg-4" >
<!--                                        <p class="fw-normal text-body text-center" style="font-size: 15px; padding: 0px; margin: 0px;"><a href="{% url 'youtube:video_edit' video.col2.id %}" class="bi bi-pen text-dark" style="font-size: 18px;"></a>&nbsp;&#8226;&nbsp;Edit</p>-->
                                    </div>
                                    <div class="col-lg-4">
                                        <p class="fw-normal text-body text-end" style="font-size: 15px; padding: 0px; margin: 0px;"><a href="{% url 'youtube:video_deletefromplaylist' video.col2.id %}" class="bi bi-trash text-dark" style="font-size: 18px;"></a>&nbsp;&#8226;&nbsp;Delete</p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endif %}
            </div>
            <div class="col-lg-4">
                {% if video.col3 %}
                    <div class="card video-content">
                        <a href="{% url 'youtube:video_view' video.col3.id %}">
                            <div class="d-flex justify-content-center" style="">
    <!--                            <iframe width="560" height="280" src={{ video.col3.source }} title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>-->
                                <img class="card-img-top" src={{ video.col3.source }} title="YouTube Video" alt="YouTube Video" width="560" height="280"/>
                            </div>
                        </a>
                        <div class="card-body">
                            {% if video.col3.title|length <= 40 %}
                                <h4 class="card-title" style="font-size: 20px; padding: 0px; margin: 0px;">{{ video.col3.title }}, You Must Watch This</h4>
                            {% else %}
                                <h4 class="card-title" style="font-size: 20px; padding: 0px; margin: 0px;">{{ video.col3.title }}</h4>
                            {% endif %}
                            <p class="text-muted" style="font-size: 14px; padding: 0px; margin-top: 10px;">Posted by {{ video.col3.user }} {{ video.col3.added|timesince }} ago</p>
                            <small class="card-text">{{ video.col3.description }}</small>
                        </div>
                        <div class="card-footer d-flex justify-content-center">
                            <div class="container" style="padding: 0px; margin: 0px;">
                                <div class="row">
                                    <div class="col-lg-4" >
                                        <p class="fw-normal text-body text-start" style="font-size: 15px; padding: 0px; margin: 0px;"><span class="bi bi-person-video2" style="font-size: 18px;"></span>{{ video.col3.views }} views</p>
                                    </div>
                                    <div class="col-lg-4" >
<!--                                        <p class="fw-normal text-body text-center" style="font-size: 15px; padding: 0px; margin: 0px;"><a href="{% url 'youtube:video_edit' video.col3.id %}" class="bi bi-pen text-dark" style="font-size: 18px;"></a>&nbsp;&#8226;&nbsp;Edit</p>-->
                                    </div>
                                    <div class="col-lg-4">
                                        <p class="fw-normal text-body text-end" style="font-size: 15px; padding: 0px; margin: 0px;"><a href="{% url 'youtube:video_deletefromplaylist' video.col3.id %}" class="bi bi-trash text-dark" style="font-size: 18px;"></a>&nbsp;&#8226;&nbsp;Delete</p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endif %}
            </div>
        </div>
        {% endfor %}
    </div>
    {% endif %}

{% endblock %}

youtube/youtube/templates/youtube/videoplaylist_confirm_delete.html
{% extends 'base.html' %}
{% load humanize %}

{% block content %}
    <div>
        <div id="video">
            <div>
<!--            <h1 class="fw-bold">YouTube Demo Application</h1>-->
<!--            <h5 class="fw-light">Watch, like and upload your own videos!</h5>-->
                <iframe width="780" height="470" src={{ video.source }} title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
                <div class="video_details">
                    <p class="fw-normal text-light" style="font-size: 20px; padding: 0px; margin: 0px;">{{ video.title }}</p>
                    <p class="fw-normal text-light" style="font-size: 12px; padding: 0px; margin: 0px;">Posted by {{ video.user }} {{ video.added|timesince }} ago</p>
                    <p class="fw-light text-light" style="font-size: 14px; padding: 0px; margin-top: 10px;">{{ video.description }}</p>
                    <div class="container">
                        <input type="hidden" name="pk" value={{video.id}} id='pk'>
                        <div class="row">
                            <div class="col-lg-4">
                                <p class="fw-normal text-light text-center" style="font-size: 15px;"><span class="bi bi-hand-thumbs-up" style="font-size: 18px;"></span><span>&nbsp;&#8226;&nbsp;{{ video.likes }} likes</span></p>
                            </div>
                            <div class="col-lg-4">
                                <p class="fw-normal text-light text-center" style="font-size: 15px;"><span class="bi bi-person-video2" style="font-size: 18px;"></span>&nbsp;{{ video.views }} views&nbsp;</p>
                            </div>
                            <div class="col-lg-4" style="padding: 0px; margin: 0px;">
                                <form method="post">
                                    {% csrf_token %}
                                    <div class="d-flex justify-content-end">
                                        <button type="submit" class="btn btn-danger text-center" style="font-size: 18px; margin-bottom: 16px;">&nbsp;Continue to delete&nbsp;</button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <br>
        <br>
    </div>

{% endblock %}