youtube/project/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('youtube.urls')),  # root/index is redirected to youtube.urls
    path('youtube-admin/', admin.site.urls),
    path(r'accounts/', include('django_registration.backends.activation.urls')),
    path(r'accounts/', include('django.contrib.auth.urls')),
]

youtube/youtube/urls.py
from django.urls import path

from . import views

app_name = 'youtube'
urlpatterns = [
    path('', views.index, name='index'),
    path('results', views.search_results, name='search_results'),
    path('video/view/<int:pk>', views.video_view, name='video_view'),
    path('video/view/like/<int:pk>', views.video_like, name='video_like'),
    path('video/myvideos', views.video_myvideos, name='video_myvideos'),
    path('video/new', views.video_new, name='video_new'),
    path('video/view/addtoplaylist/<int:pk>', views.video_addtoplaylist, name='video_addtoplaylist'),
    path('addtoplaylist/<int:pk>', views.video_addtoplaylist_fromindex, name='video_addtoplaylist_fromindex'),
    path('video/myplaylist', views.video_myplaylist, name='video_myplaylist'),
    path('video/deletefromplaylist/<int:pk>', views.video_deletefromplaylist, name='video_deletefromplaylist'),
    path('video/edit/<int:pk>', views.video_edit, name='video_edit'),
    path('video/delete/<int:pk>', views.video_delete, name='video_delete'),
]

youtube/project/templates/base.html
<!DOCTYPE html>
{% load static %}
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="django web application">
    <meta name="author" content="marvin">

    <title>YouTube demo app using Django.</title>

    <!-- Bootstrap core CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet">

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400&display=swap" rel="stylesheet">
    <style>@import url('https://fonts.googleapis.com/css2?family=Poppins:wght@300;400&display=swap');</style>

    <!-- Custom styles for this scaffold -->
    <link href="{% static 'css/site.css' %}" rel="stylesheet">
  </head>

  <body>
    <nav class="navbar sticky-top navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
            <a href="/" class="navbar-brand">
                <img src="{% static 'img/youtube.png' %}" height="50" alt="Pokemon Tournament">&nbsp&nbspYouTube Demo
            </a>
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse justify-content-end" id="navbarCollapse">
                <div class="navbar-nav">
                    <div class="navbar-nav">
                        <a href="/" class="nav-item nav-link" style="padding-right: 16px;">Home</a>
                        <div class="nav-item dropdown">
                            <a href="/" class="nav-link dropdown-toggle" data-bs-toggle="dropdown" style="padding-right: 16px;">Account</a>
                            <div class="dropdown-menu">
<!--                                <a href="{% url 'youtube:video_myvideos' %}" class="dropdown-item">My Videos</a>-->
                                <a href="/video/myvideos" class="dropdown-item">My Videos</a>
                                <a href="/video/myplaylist" class="dropdown-item">My Playlist</a>
                                <a href="/video/myvideos" class="dropdown-item">Profile</a>
                            </div>
                        </div>
                        {% if request.user.is_authenticated %}
<!--                            <a href="/" class="nav-item nav-link" style="padding-right: 16px;">API</a>-->
                            <a href="{% url 'logout' %}" class="nav-item nav-link" style="padding-right: 40px;">Logout</a>
                        {% else %}
                            <a href="/accounts/register/" class="nav-item nav-link" style="padding-right: 16px;">Register</a>
                            <a href="{% url 'login' %}" class="nav-item nav-link" style="padding-right: 40px;">Login</a>
                        {% endif %}
                    </div>
                </div>
                <form>
                    <div class="input-group">
                        <input id='search_key' type="text" class="form-control" placeholder="Search" value="">
                        <button id='search' type="button" class="btn btn-secondary"><i class="bi-search"></i></button>
                    </div>
                </form>
            </div>
        </div>
    </nav>

    <div id="main-content">
        {% block content %}{% endblock %}
    </div>

    <footer class="bg-dark text-light">
        <div>
            YouTube demo application using Django, Bootstrap 5 (HTML, CSS), AJAX, Javascript, Django ORM, Django registration and login, SendGrid Email API, SQLite database.
        </div>

        <div>
            <i class="bi bi-linkedin"></i><a href="https://linkedin.com/in/marvindswdev" style="text-decoration: none;">LinkedIn</a>
            <i class="bi bi-terminal-fill"></i><a href="https://justpython-mdelara.anvil.app/" style="text-decoration: none;">Portfolio</a>
            <i class="bi bi-envelope-fill"></i><a href = "mailto: marvin.swdev@gmail.com" style="text-decoration: none;">Send Email</a>
        </div>

        <div>
            Copyright 2023 &copy; https://justpython-mdelara.anvil.app/
        </div>
    </footer>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script
        src="https://code.jquery.com/jquery-3.7.0.min.js"
        integrity="sha256-2Pmvv0kuTBOenSvLm6bvfBSSHrUJ+3A7x6P5Ebd07/g="
        crossorigin="anonymous">
    </script>
    <script
        src="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/js/bootstrap.min.js"
        integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
        crossorigin="anonymous">
    </script>
    <script
        src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js">
    </script>
    <script>
        const like = document.getElementById('like');
        var pk = document.getElementById('pk').value;
        like.addEventListener("click", function() {
            console.log("running");
            console.log(pk);
            $.ajax({
                url : "like/" + pk.toString(),
                type : "GET",
                data : { pk : pk }, 

                // handle a successful response
                success : function(json) {
                    if (json.status == 1) {
                        document.getElementById("likes").innerText = " " + "\u2022" + " " + json.likes + " likes";
                    } else {
                        window.location.href = "{% url 'login' %}";
                    }
                },
            });
        });
    </script>
    <script>
        const add = document.getElementById('addtoplaylistfromview');
        // this is only applicable for single instance of a specific button fxn
        var pk = document.getElementById('pk').value;
        add.addEventListener("click", function() {
            console.log("running");
            console.log(pk);
            $.ajax({
                url : "addtoplaylist/" + pk.toString(),
                type : "GET",
                data : { pk : pk }, 

                // handle a successful response
                success : function(json) {
                    if (json.status == 1) {
                        window.location.href = "{% url 'youtube:video_myplaylist' %}";
                    } else {
                        window.location.href = "{% url 'login' %}";
                    }
                },
            });
        });
    </script>
    <script>
        const search = document.getElementById('search');
        var key = document.getElementById('search_key');
        search.addEventListener("click", function() {
            console.log("running");
            console.log(key.value);
            $.ajax({
                // url : "/results",  // this can be OPTIONAL if you want to just redirect like below
                // type : "GET",
                // data : { key : key.value }, // data sent with the get request

                // handle a successful response
                success : function() {
                    // console.log(videos.html);
                    // $("#videos").html(videos.html); // this needs to be an html interpretable text
                    window.location.href = "{% url 'youtube:search_results' %}" + "?key=" + key.value;
                },
            });
        });
    </script>

  </body>
</html>